# Generated by Django 3.1.5 on 2021-01-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=30)),
                ('about', models.CharField(max_length=1000)),
                ('skills', models.CharField(max_length=1000)),
                ('university', models.CharField(max_length=200)),
            ],
        ),
    ]
