# Generated by Django 3.1.5 on 2021-01-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='experience',
            field=models.CharField(default='no', max_length=500),
            preserve_default=False,
        ),
    ]
