# Generated by Django 3.1.5 on 2021-01-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_resume_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='job',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
