# Generated by Django 3.1.5 on 2021-01-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_resume_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='experience_title',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
