# Generated by Django 3.1.5 on 2021-01-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20210127_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience_title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
